%\VignetteIndexEntry{Bradley-Terry models in R}
%\VignetteKeywords{generalized linear model, logistic regression, Jeffreys prior, ranking, tournament analysis, working residuals}
%\VignettePackage{BradleyTerry2}

\documentclass[a4paper]{article}

\usepackage{Sweave}
\usepackage{amsmath}
\usepackage{txfonts} % Times, with Belleek math font and txtt for monospaced
\usepackage[scaled=0.92]{helvet}
\usepackage{booktabs}
\usepackage{color}
\usepackage[round,authoryear]{natbib}
\usepackage[left=2cm,top=2.5cm,nohead]{geometry}
\usepackage[colorlinks]{hyperref}
\definecolor{darkmagenta}{rgb}{.5,0,.5}
\hypersetup{
    colorlinks,%
    citecolor=darkmagenta,
    filecolor=darkmagenta,
    linkcolor=darkmagenta,
    urlcolor=blue
}

\setkeys{Gin}{width=0.6\textwidth}

%% The next few definitions from "Writing Vignettes for Bioconductor Packages"
%% by R Gentleman
\newcommand{\Robject}[1]{{\emph{\texttt{#1}}}}
\newcommand{\Rfunction}[1]{{\emph{\texttt{#1}}}}
\newcommand{\Rcode}[1]{{\emph{\texttt{#1}}}}
\newcommand{\Rpackage}[1]{{\textsf{#1}}}
\newcommand{\Rclass}[1]{{\emph{#1}}}
\newcommand{\Rmethod}[1]{{\emph{\texttt{#1}}}}
\newcommand{\Rfunarg}[1]{{\emph{\texttt{#1}}}}

\newcommand{\R}{\textsf{R}}
\newcommand{\s}{\textsf{S}}

\newcommand{\BT}{\Rpackage{BradleyTerry2}}

\newcommand\twiddle{{\char'176}}

\input{mymacros}

\setlength{\itemindent}{1cm}

\title{Bradley-Terry models in R: The \BT\ package}

\author{Heather Turner and David Firth\\{\it University of Warwick, UK}\\
\\
\url{http://go.warwick.ac.uk/heatherturner}}

\date{For \Rpackage{BradleyTerry2} version \Sexpr{packageDescription("BradleyTerry2")[["Version"]]}, \Sexpr{Sys.Date()}}

\begin{document}

\maketitle

\abstract{\small

This is a short overview of the \R\ add-on package \BT, which facilitates the
specification and fitting of Bradley-Terry logit, probit or cauchit
models to pair-comparison data.
Included are the standard `unstructured' Bradley-Terry model, structured
versions in which the parameters are related through a linear predictor to
explanatory variables, and the possibility of an order or `home advantage'
effect or other `contest-specific' effects.
Model fitting is either by maximum likelihood, by penalised
quasi-likelihood (for models which involve a random effect), or by bias-reduced
maximum likelihood in which the first-order asymptotic bias of parameter
estimates is eliminated.  Also  provided are a simple and efficient approach to
handling missing covariate data, and suitably-defined residuals for diagnostic
checking of the linear predictor.
}

\bigskip
\noindent
{\small
\textbf{Key words}:
generalized linear model, logistic regression, Jeffreys prior, penalised quasi-likelihood, ranking, tournament analysis, working residuals}

\section{Bradley-Terry model}

\subsection{Introduction}

The Bradley-Terry model \citep{brad:terr:52} assumes that in a `contest' between
any two `players', say player $i$ and player $j$ $(i, j \in \{1,\ldots,K\})$,
the odds that $i$ beats $j$ is $\alpha_i/\alpha_j$, where $\alpha_i$ and
$\alpha_j$ are positive-valued parameters which might be thought of as
representing `ability'.  For a good general introduction see \citet{agre:02}.
Applications are many, ranging from experimental psychology to the analysis of
sports tournaments to genetics (for example, the allelic
transmission/disequilibrium test of \citet{sham:curt:95} is based on a
Bradley-Terry model in which the `players' are alleles).    The model can
alternatively be expressed in the logit-linear form
\begin{equation}
\logit[\pr(i\ \mathrm{beats}\ j)]=\lambda_i-\lambda_j,
\end{equation}
where $\lambda_i=\log\alpha_i$ for all $i$.  Thus, assuming independence of all
contests, the parameters $\{\lambda_i\}$ can be estimated by
maximum likelihood using standard software for generalized linear models, with a
suitably specified model matrix.  The primary purpose of the \BT\ package,
implemented in the \R\ statistical computing environment \citep{ihak:gent:96,
  R}, is to facilitate the specification and fitting of such models, including
special cases in which the ability parameters are related to available
explanatory variables through a linear predictor of the form
$\lambda_i=\sum_{r=1}^p\beta_rx_{ir} + U_i$.  The logit link can be replaced,
if required, by a different symmetric link function (probit or cauchit).



\subsection{Example: analysis of journal citations}
\label{citations}

The following comes from page 448 of \citet{agre:02}, extracted from the larger
table of \citet{stig:94}.  The data are counts of citations among four prominent
journals of statistics and are included the \BT\ package as the dataset
\Robject{citations}:
@
<<CitationData>>=
library(BradleyTerry2)
data(citations)
@
\newpage
@
<<CitationData2>>=
citations
@ %def
Thus, for example, \emph{Biometrika} was cited 498 times by papers in
\emph{JASA} during the period under study.  In order to fit a Bradley-Terry
model to these data using \Rfunction{BTm} from the \BT\ package, the data must
first be converted to binomial frequencies. That is, the data need to be
organised into pairs (\Robject{player1}, \Robject{player2}) and corresponding
frequencies of wins and losses for \Robject{player1} against
\Robject{player2}. The \BT\ package provides the utility function
\Rfunction{countsToBinomial} to convert a contingency table of
wins to the format just described:
@
<<countsToBinomial>>=
citations.sf <- countsToBinomial(citations)
names(citations.sf)[1:2] <- c("journal1", "journal2")
citations.sf
@ %def

The binomial response can then be modelled by the difference in player abilities
as follows:
@
<<citeModel>>=
citeModel <- BTm(cbind(win1, win2), journal1, journal2, ~ journal, id = "journal", data = citations.sf)
citeModel
@ %def
The coefficients here are maximum likelihood estimates of $\lambda_2, \lambda_3,
\lambda_4$, with $\lambda_1$ (the log-ability for \emph{Biometrika}) set to zero
as an identifying convention.

The one-sided model formula
\begin{verbatim}
      ~ journal
\end{verbatim}
specifies the model for player ability, in this case the `citeability' of the
journal. The \Rfunarg{id} argument specifies that \code{"journal"} is the
name to be used for the factor that identifies the player --- the values of which
are given here by \Rcode{journal1} and \Rcode{journal2} for the first and
second players respectively. Therefore in this case a separate
citeability parameter is estimated for each journal. 

If a different `reference' journal is required, this can be achieved using the
optional \Rfunarg{refcat} argument: for
example, making use of \Rfunction{update} to avoid re-specifying the whole model,
@
<<citeModelupdate>>=
update(citeModel, refcat = "JASA")
@ %def
--- the same model in a different parameterization.

The use of the standard Bradley-Terry model for this application might perhaps
seem rather questionable --- for example, citations within a published paper can
hardly be considered independent, and the model discards potentially important
information on self-citation.  \citet{stig:94} provides arguments to defend the
model's use despite such concerns.

\section{Abilities predicted by explanatory variables}

\subsection{`Player-specific' predictor variables}

In some application contexts there may be `player-specific' explanatory
variables available, and it is then natural to consider model simplification of
the form
\begin{equation}
\lambda_i=\sum_{r=1}^p\beta_rx_{ir} + U_i,
\end{equation}
in which ability of each player $i$ is related to explanatory variables
$x_{i1},\ldots,x_{ip}$ through a linear predictor with coefficients
$\beta_1,\ldots,\beta_p$; the $\{U_i\}$ are independent errors.
See, for example, \citet{spri:73} (but note that the error term $U_i$ is
omitted there). Dependence of
the player abilities on explanatory variables can be specified via the
\Rfunarg{formula} argument, using the standard \emph{S}-language
model formulae.  The difference in the abilities of player $i$
and player $j$ is modelled by
\begin{equation}
\sum_{r=1}^p\beta_rx_{ir} - \sum_{r=1}^p\beta_rx_{jr} + U_i - U_j,
\end{equation}
where $U_i \sim N(0, \sigma^2)$ for all $i$. The Bradley-Terry model is then a
generalized linear mixed model, which the \Rfunction{BTm} function currently
fits using the penalized quasi-likelihood algorithm of \citet{bres:93}.

As a simple illustration, consider the
response-surface model studied by \citet{spri:73}:
@
<<springall>>=
options(show.signif.stars = FALSE)
data(springall)
summary(springall.model <- BTm(cbind(win.adj, loss.adj), col, row,
                               ~ flav[..] + gel[..] +
                                 flav.2[..] + gel.2[..] + flav.gel[..] +
                                 (1 | ..),
                               data = springall))
@ %def
Differences from the fit reported in \cite{spri:73} are minor, arising from
the different treatment of ties: here we have simply treated a tie as half a
`win' for each `player', rather than using the \cite{rao:kupp:67} model as
\cite{spri:73} did.

In \cite{spri:73}, the random effect (specified here via the term
\Rcode{(1|..)}) was omitted: that is, the quadratic response
surface was assumed to predict `ability' without error.  In general such a
zero-error assumption will be unrealistic.  In this instance, though,
including the random
term turns out to make no difference to the results: the variance of the errors $\{U_i\}$ is
estimated as zero.

The special name \Rcode{``..''} appears here as the default identifier for
players, in the absence of a user-specified \Rfunarg{id} argument.  The
predictor variables in this case are taken from the
\Robject{springall\$predictors} data frame, whose rows are indexed by the
levels of \Rcode{``..''}.

\subsection{Missing values}

The contest data may include all possible pairs of players and hence rows of
missing data corresponding to players paired with themselves. Such rows
contribute no information to the Bradley-Terry model and are simply discarded by
\Rfunction{BTm}.

Where there are missing values in player-specific \emph{predictor} (or
\emph{explanatory}) variables which appear in the formula, it
will typically be very wasteful to discard all contests involving players for
which some values are missing. Instead, such cases are accommodated by the
inclusion of one or more parameters in the model.  If, for example, player $1$
has one or more of its predictor values $x_{11},\ldots,x_{1p}$ missing, then the
combination of (1) and (3) above yields
\[
\logit[\pr(1\ \mathrm{beats}\ j)]=\lambda_1 - \left(\sum_{r=1}^p\beta_rx_{jr} + U_j\right),
\]
for all other players $j$.  This results in the inclusion of a `direct' ability
parameter for each player having missing predictor values, in addition to the
common coefficients $\beta_1,\ldots,\beta_p$ --- an approach which will be
appropriate when the missingness mechanism is unrelated to contest success.  The
same device can be used also to accommodate any user-specified departures from a
structured Bradley-Terry model, whereby some players have their abilities
determined by the linear predictor but others do not.

For an illustration of this device in action, see \Rcode{example(flatlizards)}:
two of the lizards in that study (\Robject{lizard096} and \Robject{lizard099})
have some missing covariate data, and those two lizards therefore have their
abilities estimated by separate coefficients.

\subsection{Order effect}

In certain types of application some or all contests have an associated `bias',
related to the order in which items are presented to a judge or with the
location in which a contest takes place, for example.  A natural extension of
the Bradley-Terry model (1) is then
\[
\logit[\pr(i\ \mathrm{beats}\ j)]=\lambda_i-\lambda_j + \delta z,
\]
where $z=1$ if $i$ has the supposed advantage and $z=-1$ if $j$ has it.  (If the
`advantage' is in fact a disadvantage, $\delta$ will be negative.)  The scores
$\lambda_i$ then relate to ability in the absence of any such advantage.

As an example, consider the baseball data given in \citet{agre:02}, p438:
@
<<baseball>>=
data(baseball)
head(baseball)
@ %def
The dataset records the home wins and losses for each baseball team against each
of the 6 other teams in the dataset. The \Rfunction{head} function is used to
show the first 6 records, which are the Milwaukee home games. We see for
example that Milwaukee played 7 home games against Detroit and won 4 of them.
The `standard' Bradley-Terry model without a home-advantage parameter will be
fitted if no formula is specified in the call to \Rfunction{BTm}:
@
<<baseballModel>>=
data(baseball)
baseballModel1 <- BTm(cbind(home.wins, away.wins), home.team, away.team,
                      data = baseball, id = "team")
summary(baseballModel1)
@ %def
The reference team is Baltimore, estimated to be the weakest of these seven,
with Milwaukee and Detroit the strongest.

To estimate the home-advantage effect, the \Robject{home.team} and
\Robject{away.team} factors need to be replaced by data frames specifying an
\Rcode{at.home} variable in addition to the factor identifying the players,
which should be named according to the \Rfunarg{id} argument: 
@
<<baseballDataUpdate>>=
baseball$home.team <- data.frame(team = baseball$home.team, at.home = 1)
baseball$away.team <- data.frame(team = baseball$away.team, at.home = 0)
@ %def
The \Rcode{at.home} variable is needed for both the home team and 
away team, so that it can be differenced as appropriate in the linear
predictor.
@
<<baseballModelupdate>>=
baseballModel2 <- update(baseballModel1, formula = ~ team + at.home)
summary(baseballModel2)
@ %def
This reproduces the results given on page 438 of \citet{agre:02}: the home team
has an estimated odds-multiplier of $\exp(0.3023) = 1.35$ in its favour.

\subsection{More general (contest-specific) predictors}

The `home advantage' effect is an simple
example of a contest-specific predictor.  Such predictors are necessarily
interaction terms, between aspects of the contest and (aspects of) the two
`players' involved.

For more elaborate examples of such effects, see \Rcode{?chameleons} and
\Rcode{?CEMS}.  The former includes an `experience' effect, which changes
through time, on the fighting ability of male chameleons.  The latter
illustrates a common situation in psychometric applications of the
Bradley-Terry model, where \emph{subjects} express preference for one of two
\emph{objects} (the `players'), and it is the influence on the results of
subject attributes that is of primary interest.

As an illustration of the way in which such effects are specified, consider
the following model specification taken from the examples in \Rcode{?CEMS}:
@
<<CEMSmodel>>=
data(CEMS)
table8.model <-  BTm(outcome = cbind(win1.adj, win2.adj),
                     player1 = school1, player2 = school2,
                     formula = ~ .. +
                         WOR[student] * LAT[..] +
                         DEG[student] * St.Gallen[..] +
                         STUD[student] * Paris[..] +
                         STUD[student] * St.Gallen[..] +
                         ENG[student] * St.Gallen[..] +
                         FRA[student] * London[..] +
                         FRA[student] * Paris[..] +
                         SPA[student] * Barcelona[..] +
                         ITA[student] * London[..] +
                         ITA[student] * Milano[..] +
                         SEX[student] * Milano[..],
                     refcat = "Stockholm",
                     data = CEMS)
@ %def
Here the subjects are students, and the objects
(six European management schools) are referenced by \Rcode{``..''}.  The
subject-specific variables \Robject{WOR}, \Robject{DEG}, etc., are found in the  data frame \Robject{CEMS\$students} which contains student-specific
variables; the variable \Robject{LAT}, for example, is in the data frame \Robject{CEMS\$schools} which contains school-specific variables.


\section{Ability scores}

The function \Rfunction{BTabilities} extracts estimates and standard errors for
the log-ability scores $\lambda_1, \ldots,\lambda_K$.  These will either be
`direct' estimates, in the case of the standard Bradley-Terry model or for
players with one or more missing predictor values, or `model-based' estimates
of the form $\hat\lambda_i=\sum_{r=1}^p\hat\beta_rx_{ir}$ for players whose ability is
predicted by explanatory variables.

As a simple illustration, team ability estimates in the
home-advantage model for the \Robject{baseball} data are obtained by:
@
<<BTabilities>>=
BTabilities(baseballModel2)
@ %def
This gives, for each team, the estimated ability when the team
enjoys no home advantage.

Similarly, ability estimates (for the nine experimental settings found in \Robject{springall.predictors}) can be obtained for the response-surface model of
\cite{spri:73}:
@
<<BTabilities2>>=
BTabilities(springall.model)
@ %def

The ability estimates in an un-structured Bradley-Terry model are particularly well suited to presentation using the device of \emph{quasi variances} \citep{firt:04}.  The \Rpackage{qvcalc} package (version 0.8-5 or later) contains a function of the same name which does the necessary work:
\begin{Sinput}
> library(qvcalc)
> baseball.qv <- qvcalc(BTabilities(baseballModel2))
> plot(baseball.qv, levelNames = c("Bal", "Bos", "Cle", "Det", "Mil", "NY", "Tor"))
\end{Sinput}
\begin{figure}[!tbph]
    \begin{center}
        \includegraphics{baseball-qvplot.pdf}
    \end{center}
    \caption{Estimated relative abilities of baseball teams}
    \label{fig:qvplot}
\end{figure}

\section{Residuals}

There are two main types of residuals available for a Bradley-Terry model object.

First, there are residuals obtained by the standard methods for models of class
\Robject{"glm"}.  These all deliver one residual for each contest or type of
contest.  For example, Pearson residuals for the model
\Robject{springall.model} can be obtained simply by
@
<<residuals>>=
res.pearson <- round(residuals(springall.model), 3)
head(cbind(springall$contests, res.pearson))
@ %def

More useful for diagnostics on the linear predictor $\sum\beta_rx_{ir}$ are
`player'-level residuals, obtained by using the function \Rfunction{residuals}
with argument \Rfunarg{type = "grouped"}.  These residuals can then be
plotted against other player-specific variables.
@
<<BTresiduals>>=
res <- residuals(springall.model, type = "grouped")
#  with(springall$predictors, plot(flav, res))
#  with(springall$predictors, plot(gel, res))
@ %def
These residuals estimate the error in the linear predictor; they are obtained by
suitable aggregation of the so-called `working' residuals from the model fit.
The \Robject{weights} attribute
indicates the relative information in these residuals --- weight is roughly
inversely proportional to variance --- which may be useful for plotting and/or
interpretation; for example, a large residual may be of no real concern if based
on very little information. Weighted least-squares regression of these residuals
on any variable already in the model is null.  For example:
@
<<residualWLS>>=
lm(res ~ flav, weights = attr(res, "weights"), data = springall$predictors)
lm(res ~ gel, weights = attr(res, "weights"), data = springall$predictors)
@ %def %$

\section{Bias-reduced estimates}

Estimation of the Bradley-Terry model in \Rpackage{BTm} is by default
(when there are no random effects in the model)
computed by maximum likelihood, using an internal call to the
\Rfunction{glm} function.  An alternative  is to fit by bias-reduced
maximum likelihood \citep{firt:93}: this requires additionally the
\Rpackage{brglm}
package, and is specified by the optional argument \Rfunarg{br = TRUE}.  The
resultant effect, namely removal of first-order asymptotic bias in
the estimated coefficients, is often quite small.  One notable feature of
bias-reduced fits is that all estimated coefficients and standard errors are
necessarily finite, even in situations of `complete separation' where MLEs take
infinite values \citep{hein:sche:02}.

\section{Model search}

In addition to \Rfunction{update()} as illustrated above, methods for the
generic functions \Rfunction{add1()}, \Rfunction{drop1()} and
\Rfunction{anova()} are provided. These
can be used to investigate the effect of adding or removing a variable, whether
that variable is contest-specific, such as an order effect, or player-specific;
and to compare the fit of nested models.

%These can be used in the standard way for model elaboration or specialization,
%and their availability also allows the use of \texttt{\color{black} step()} for
%automated exploration of a set of candidate player-specific predictors.

\section{Setting up the data}

\subsection{Contest-specific data}

The \Rfunarg{outcome} argument of \Rfunction{BTm} represents a
binomial response and can be supplied in any of the formats allowed by the
\Rfunction{glm} function. That is, either a two-column matrix with the columns
giving the number of wins and losses (for \Rfunarg{player1}), a factor where
the first level denotes a
loss and all other levels denote a win, or a binary variable where 0 denotes a
loss and 1 denotes a win. Each row represents either a single contest or a set
of contests between the same two players.

Any \emph{contest-specific} variables should be of the
same length as the variables specified in the \Rfunarg{outcome},
\Rfunarg{player1} and \Rfunarg{player2} arguments.  Sometimes this is
achieved most economically by appropriate indexing: see, for example,
\Rcode{?CEMS}, where student-specific variables are stored in a data frame
with one row per student rather than one row per `contest'.

An offset in the model can be specified by
using the \Rfunarg{offset} argument to \Rfunction{BTm}.

To use only certain rows of the data in the analysis, the \Rfunarg{subset}
argument may be used in the call to \Rfunction{BTm}.  This should either be a
logical vector of the same length as the binomial response, or a numeric vector
containing the indices of rows to be used.

\subsection{Player-specific data}

Variables indexed by the levels of \Rfunarg{player1} and \Rfunarg{player2},
i.e., indexed by \Rfunarg{id}, are said to be `player-specific'.
The safest approach is to put all potential predictor
(explanatory) variables  --- including factors and any offset term --- into a
data frame with one row per (potential) player,
and with row names the names of players exactly as used in variables passed to
the \Rfunarg{player1} and \Rfunarg{player2} arguments of \Rfunction{BTm}.
Such data frame
should then be included in the list specified as the \Rfunarg{data} argument
of \Rfunction{BTm} to specify where predictors (and any offset) can be found.

\subsection{Converting data from the format required by the earlier \Rpackage{BradleyTerry} package}

The \Rpackage{BradleyTerry} package described in \citet{firt:05} required contest/comparison results to be in a data frame with columns named \Robject{winner}, \Robject{loser} and \Robject{Freq}.  The following example shows how \Rfunction{xtabs} and \Rfunction{countsToBinomial} can be used to convert such data for use with the \Rfunction{BTm} function in \Rpackage{BradleyTerry2}:
\begin{Sinput}
> library(BradleyTerry)  ## the /old/ BradleyTerry package
> data(citations, package = "BradleyTerry")  ## data frame with columns "winner", "loser", "Freq"
> citations <- xtabs(Freq ~ winner + loser, citations)  ## convert to 2-way table of counts
> citations.sf <- countsToBinomial(citations)  ## convert to a data frame of binomial observations
\end{Sinput}
The \Robject{citations.sf} data frame can then be used with \Rfunction{BTm} as shown in Section \ref{citations}.



\section[A list of the functions provided in BradleyTerry2]{A list of the functions provided in \BT}

The standard \R\ help files provide the definitive reference.  Here we simply
list the main user-level functions and their arguments, as a
convenient overview:
@
<<functions, echo = FALSE>>=
## cf. prompt
for (fn in getNamespaceExports("BradleyTerry2")) {
    name <- as.name(fn)
    args <- formals(fn)
    n <- length(args)
    arg.names <- arg.n <- names(args)
    arg.n[arg.n == "..."] <- "\\dots"
    is.missing.arg <- function(arg) typeof(arg) == "symbol" &&
        deparse(arg) == ""
    Call <- paste(name, "(", sep = "")
        for (i in seq_len(n)) {
        Call <- paste(Call, arg.names[i], if (!is.missing.arg(args[[i]]))
            paste(" = ", paste(deparse(args[[i]]),
                collapse = "\n"), sep = ""), sep = "")
        if (i != n)
            Call <- paste(Call, ", ", sep = "")
    }
    Call <- paste(Call, ")", sep = "")
    cat(deparse(parse(text = Call)[[1]]), fill = TRUE)
}
@ %def

\section[A note on the treatment of ties]{A note on the treatment of ties}

The present version of \BT\ provides no sophisticated facilities for handling
tied contests/comparisons; the well-known models of \cite{rao:kupp:67}
and \cite{davi:70} are not implemented here.  At present the \Rfunction{BTm}
function requires a binary or binomial response variable, the third (`tied')
category of response is not allowed.

In several of the data examples (e.g., \Rcode{?CEMS}, \Rcode{?springall},
\Rcode{?sound.fields}),
ties are handled by the crude but simple device of adding half of a `win' to
the tally for each player involved; in each of the examples where this has been done it is found that the result is very similar, after a simple re-scaling, to the more sophisticated analyses that have appeared in the literature.

It is likely that a future version of \BT\ will have a more general method for handling ties.

\section*{Acknowledgment}

This work was supported by the UK Engineering and Physical Sciences Research
Council.


\bibliography{BradleyTerry}
\bibliographystyle{chicago}

\end{document}
\end

